### PR TITLE
Bootstrap sh cleanup v1

### PR DESCRIPTION
**Pull request by dev-239**
Minor fixes only
- Moved logging to its own dir (and added to gitignore).
- Script path var was only partialy used, removed it.
- Added full list of python requirements.

### CODE REVIEW

**Comment by frbor** [comment]
I would like to keep SCRIPT_PATH (although it might be renamed to BOOTSTRAP_HOME or similar), since then the script can be called from other locations, and the links towards types/ will still be correct. In fact, I propose to use the same reference in the newly merged `sort-types.sh`, so this script can be executed both from scripts and from the root directory of the repository, so if you want to, please add the same logic there.

For requriments.txt it could be discussed whether we should pin all the versions of the libraries, but at this stage I'm not sure if that is desireable? We might want to pin act-api (to version 0.5.1), but other requirements should most likely use the latest available version. Of course, pyexcel should also be added, since that one was missing.

**Comment by dev-239** [comment]
Keeping the SCRIPT_PATH as a concept seems like a good idea after reading your explanation. When running on my macOS platform i encountered some issues, so i will just have to look into the error messages i got.

With regards to the versioning in "requirements.txt" i think that what you proposed will work very well at this stage of the project. From what i see there is a rapid development ongoing, and it seems correct to stay at the "bleeding-edge" of the other projects in the ACT project. These requirements could in the future be pinned-down when things stabilize.

I think it is best to close this PR, then we can come back with separate PRs.
- act-bootstrap.sh (updates as brought up in this PR).
- sort-types.sh (implementing script_path concept as mentioned)
- python requirements (adding all requirements but not pinning versions for everything).

**Comment by frbor** [comment]
It looks like `readlink -f` is not supported on osx.

It will most likely work to replace that line with this:

```
SCRIPT_PATH=`dirname $(readlink -f $0)`
```
with
```
SCRIPT_PATH=`dirname $0`
```

**Comment by frbor** [comment]
You can have a look at [PR7](https://github.com/mnemonic-no/act-bootstrap/pull/7) where I have removed use of readlink and implemented the same logic in sort-types.sh.

**Comment by dev-239** [comment]
Ah, nice, #7  fixed the issues i had. Will close this, then apply the changes i had atop of master after a merge of #7.

**Pull request closed without merging**
